{% set name = "osmapi" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/osmapi-{{ version }}.tar.gz
  sha256: ec0be6550b86bdb6369fd2f766563c22875f75a516a2526bfa0c2950d3c1feb2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    # - pypandoc
    # - unidecode
  run:
    - python >=3.6
    - requests

test:
  imports:
    - osmapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metaodi/osmapi
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Python wrapper for the OSM API

extra:
  recipe-maintainers:
    - ocefpaf
