{% set name = "osmapi" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/osmapi-{{ version }}.tar.gz
  sha256: 7b51804f8d0da953376cdfb6f9cfcb79b501312e535b31c654d213d9b46f0270

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    # - pypandoc
    # - unidecode
  run:
    - python >=3.6
    - requests

test:
  imports:
    - osmapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metaodi/osmapi
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Python wrapper for the OSM API

extra:
  recipe-maintainers:
    - ocefpaf
