{% set version = "2.0.0" %}

package:
  name: osmapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/osmapi/osmapi-{{ version }}.tar.gz
  sha256: bb2242d9c540a2ef1e7a9ddfaf6d3d0be7731af6657b6848df905179a9f51965

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - osmapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metaodi/osmapi
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Python wrapper for the OSM API

extra:
  recipe-maintainers:
    - ocefpaf
